import type { DemoScenario } from '@showcase/shared';

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'ecom',
    title: 'E-Commerce Bot',
    subtitle: 'Магазин в Telegram',
    description: 'Полноценный интернет-магазин в боте: каталог, корзина, оплата, доставка, повторные покупки, программа лояльности.',
    icon: '🛍️',
    gradient: 'from-violet-600 via-purple-600 to-indigo-700',
    tags: ['shop', 'payments', 'loyalty', 'automation'],
    metrics: [
      { label: 'Конверсия в покупку', value: '23%', delta: '+8%', trend: 'up' },
      { label: 'Средний чек', value: '3 200 ₽', delta: '+450 ₽', trend: 'up' },
      { label: 'Повторные покупки', value: '67%', delta: '+12%', trend: 'up' },
      { label: 'CAC', value: '180 ₽', delta: '-40 ₽', trend: 'up' },
    ],
    steps: [
      { id: 'catalog', title: 'Каталог товаров', description: 'Пользователь открывает бота, видит интерактивный каталог с фото и ценами', type: 'bot', durationMs: 1200 },
      { id: 'product', title: 'Карточка товара', description: 'WebApp открывается с полным описанием, галереей и кнопкой "В корзину"', type: 'webapp', durationMs: 800 },
      { id: 'cart', title: 'Корзина и оформление', description: 'Динамическая корзина с расчётом стоимости и выбором доставки', type: 'webapp', durationMs: 1000 },
      { id: 'payment', title: 'Оплата Telegram Pay', description: 'Встроенная оплата без перехода на сторонние сайты', type: 'payment', durationMs: 1500 },
      { id: 'notification', title: 'Подтверждение и трекинг', description: 'Автоматические уведомления о статусе заказа и доставке', type: 'notification', durationMs: 600 },
      { id: 'analytics', title: 'Аналитика продаж', description: 'Дашборд с выручкой, конверсией по каналам, LTV клиентов', type: 'analytics', durationMs: 800 },
    ],
  },
  {
    id: 'club',
    title: 'Club & Community',
    subtitle: 'Закрытый клуб подписчиков',
    description: 'Платный клуб с контентом, геймификацией, командами, рейтингами и автоматическим управлением доступом.',
    icon: '🏆',
    gradient: 'from-amber-500 via-orange-500 to-rose-600',
    tags: ['subscription', 'gamification', 'content', 'community'],
    metrics: [
      { label: 'MRR', value: '₽ 840K', delta: '+₽120K', trend: 'up' },
      { label: 'Churn rate', value: '4.2%', delta: '-1.8%', trend: 'up' },
      { label: 'DAU/MAU', value: '71%', delta: '+15%', trend: 'up' },
      { label: 'NPS', value: '74', delta: '+11', trend: 'up' },
    ],
    steps: [
      { id: 'funnel', title: 'Воронка продаж', description: 'Бот ведёт пользователя через персонализированный путь к оплате', type: 'bot', durationMs: 1400 },
      { id: 'payment', title: 'Подписка', description: 'Автоматическое списание и управление доступом к каналам', type: 'payment', durationMs: 1000 },
      { id: 'onboarding', title: 'Онбординг', description: 'WebApp встречает участника, показывает путь и первые задания', type: 'webapp', durationMs: 1200 },
      { id: 'content', title: 'Контент и курсы', description: 'Видео, практики, стримы с прогрессом и XP за каждый урок', type: 'webapp', durationMs: 800 },
      { id: 'gamification', title: 'Геймификация', description: 'Уровни, стрики, достижения, командный рейтинг по городам', type: 'webapp', durationMs: 600 },
      { id: 'analytics', title: 'Метрики клуба', description: 'MRR, churn, активность, top-performers, retention когорты', type: 'analytics', durationMs: 800 },
    ],
  },
  {
    id: 'service',
    title: 'Service Automation',
    subtitle: 'Автоматизация сервиса',
    description: 'Бот для лидогенерации, квалификации заявок, ответов на FAQ и передачи в CRM без участия менеджера.',
    icon: '⚡',
    gradient: 'from-emerald-500 via-teal-500 to-cyan-600',
    tags: ['leads', 'crm', 'automation', 'support'],
    metrics: [
      { label: 'Лидов в день', value: '340', delta: '+120', trend: 'up' },
      { label: 'Время ответа', value: '< 3 сек', delta: '-97%', trend: 'up' },
      { label: 'Автозакрытие FAQ', value: '78%', delta: '+23%', trend: 'up' },
      { label: 'Экономия ФОТ', value: '₽ 210K/мес', trend: 'up' },
    ],
    steps: [
      { id: 'lead', title: 'Захват лида', description: 'Бот встречает пользователя по реферальной ссылке с UTM', type: 'bot', durationMs: 1000 },
      { id: 'qualify', title: 'Квалификация', description: 'Серия вопросов для определения сегмента и потребности', type: 'bot', durationMs: 1200 },
      { id: 'webapp', title: 'Форма заявки', description: 'WebApp с динамической формой под сегмент клиента', type: 'webapp', durationMs: 800 },
      { id: 'crm', title: 'Передача в CRM', description: 'Автоматическая передача лида с оценкой в GetCourse/Bitrix', type: 'notification', durationMs: 600 },
      { id: 'followup', title: 'Follow-up воронка', description: 'Авто-серия сообщений на основе действий лида', type: 'bot', durationMs: 1000 },
      { id: 'analytics', title: 'Воронка лидов', description: 'Источники, конверсия по этапам, ROI по каналам', type: 'analytics', durationMs: 800 },
    ],
  },
  {
    id: 'education',
    title: 'EdTech Platform',
    subtitle: 'Обучение в Telegram',
    description: 'Образовательная платформа с курсами, тестами, домашними заданиями, сертификатами и аналитикой прогресса.',
    icon: '🎓',
    gradient: 'from-blue-600 via-indigo-600 to-violet-700',
    tags: ['courses', 'tests', 'certificates', 'progress'],
    metrics: [
      { label: 'Completion rate', value: '83%', delta: '+28%', trend: 'up' },
      { label: 'Активных учеников', value: '2 400', delta: '+600', trend: 'up' },
      { label: 'Оценка курса', value: '4.8/5', trend: 'neutral' },
      { label: 'Время на урок', value: '18 мин', delta: '+4 мин', trend: 'up' },
    ],
    steps: [
      { id: 'enroll', title: 'Запись на курс', description: 'Выбор курса, оплата, мгновенный доступ через бота', type: 'bot', durationMs: 1000 },
      { id: 'lesson', title: 'Урок с медиа', description: 'Видео + текст + практика в одном экране WebApp', type: 'webapp', durationMs: 1400 },
      { id: 'quiz', title: 'Интерактивный тест', description: 'Quiz с объяснением ответов и XP за правильные', type: 'webapp', durationMs: 800 },
      { id: 'homework', title: 'Домашнее задание', description: 'Отправка ДЗ через бота, авто-проверка и фидбек', type: 'bot', durationMs: 600 },
      { id: 'certificate', title: 'Сертификат', description: 'Генерация PDF-сертификата с именем и QR-кодом', type: 'notification', durationMs: 1000 },
      { id: 'analytics', title: 'Прогресс-аналитика', description: 'Успеваемость группы, отстающие, best performers', type: 'analytics', durationMs: 800 },
    ],
  },
  {
    id: 'support',
    title: 'Support Desk',
    subtitle: 'Поддержка клиентов',
    description: 'AI-тикетная система поддержки с автоответами, эскалацией, SLA-контролем и базой знаний.',
    icon: '🎯',
    gradient: 'from-pink-600 via-rose-500 to-red-600',
    tags: ['support', 'ai', 'tickets', 'sla'],
    metrics: [
      { label: 'CSAT', value: '94%', delta: '+9%', trend: 'up' },
      { label: 'Среднее время закрытия', value: '4.2 ч', delta: '-3.1 ч', trend: 'up' },
      { label: 'AI-закрытые тикеты', value: '61%', trend: 'neutral' },
      { label: 'SLA соблюдение', value: '99.1%', delta: '+4%', trend: 'up' },
    ],
    steps: [
      { id: 'ticket', title: 'Создание тикета', description: 'Пользователь описывает проблему, AI классифицирует и приоритизирует', type: 'bot', durationMs: 1200 },
      { id: 'ai_answer', title: 'AI-ответ', description: 'Мгновенный ответ из базы знаний с релевантностью 94%', type: 'bot', durationMs: 800 },
      { id: 'escalation', title: 'Эскалация', description: 'Если AI не решил — тикет уходит агенту с контекстом', type: 'notification', durationMs: 600 },
      { id: 'webapp', title: 'Трекинг тикета', description: 'WebApp с историей переписки и статусом в реальном времени', type: 'webapp', durationMs: 1000 },
      { id: 'resolution', title: 'Закрытие и оценка', description: 'Автозапрос оценки и NPS через бота после решения', type: 'bot', durationMs: 600 },
      { id: 'analytics', title: 'SLA дашборд', description: 'CSAT, время ответа, категории обращений, нагрузка агентов', type: 'analytics', durationMs: 800 },
    ],
  },
  {
    id: 'funnel',
    title: 'Growth Funnels',
    subtitle: 'Воронки и автоматизация',
    description: 'Многошаговые воронки с A/B тестами, сегментацией, delay-логикой и атрибуцией по UTM.',
    icon: '🚀',
    gradient: 'from-fuchsia-600 via-pink-600 to-rose-700',
    tags: ['funnel', 'ab-test', 'attribution', 'automation'],
    metrics: [
      { label: 'Конверсия воронки', value: '34%', delta: '+11%', trend: 'up' },
      { label: 'A/B uplift', value: '+19%', trend: 'up' },
      { label: 'Стоимость лида', value: '₽ 85', delta: '-₽35', trend: 'up' },
      { label: 'ROI', value: '380%', delta: '+120%', trend: 'up' },
    ],
    steps: [
      { id: 'traffic', title: 'Трафик по UTM', description: 'Трекинг-ссылки с UTM, A/B группами и GeoIP атрибуцией', type: 'analytics', durationMs: 1000 },
      { id: 'landing', title: 'Бот-лендинг', description: 'Персонализированный старт бота по параметрам ссылки', type: 'bot', durationMs: 1200 },
      { id: 'nurture', title: 'Nurture-серия', description: 'Авто-сообщения с задержкой: 5 мин, 1 час, 1 день', type: 'bot', durationMs: 800 },
      { id: 'ab_test', title: 'A/B оффер', description: 'Разные офферы для сегментов с измерением конверсии', type: 'webapp', durationMs: 1000 },
      { id: 'conversion', title: 'Конверсионное действие', description: 'Оплата, регистрация или другое целевое действие', type: 'payment', durationMs: 600 },
      { id: 'analytics', title: 'Attribution report', description: 'Полный путь: клик → бот → оплата с источником и стоимостью', type: 'analytics', durationMs: 800 },
    ],
  },
];
